// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protocol.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerKind identifies the type of message sent from Go to the browser.
type ServerKind int32

const (
	ServerKind_SERVER_INIT      ServerKind = 0
	ServerKind_SERVER_PATCH     ServerKind = 1
	ServerKind_SERVER_JSCALL    ServerKind = 2
	ServerKind_SERVER_STREAM    ServerKind = 3 // future
	ServerKind_SERVER_BROADCAST ServerKind = 4 // future
)

// Enum value maps for ServerKind.
var (
	ServerKind_name = map[int32]string{
		0: "SERVER_INIT",
		1: "SERVER_PATCH",
		2: "SERVER_JSCALL",
		3: "SERVER_STREAM",
		4: "SERVER_BROADCAST",
	}
	ServerKind_value = map[string]int32{
		"SERVER_INIT":      0,
		"SERVER_PATCH":     1,
		"SERVER_JSCALL":    2,
		"SERVER_STREAM":    3,
		"SERVER_BROADCAST": 4,
	}
)

func (x ServerKind) Enum() *ServerKind {
	p := new(ServerKind)
	*p = x
	return p
}

func (x ServerKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerKind) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_enumTypes[0].Descriptor()
}

func (ServerKind) Type() protoreflect.EnumType {
	return &file_protocol_proto_enumTypes[0]
}

func (x ServerKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerKind.Descriptor instead.
func (ServerKind) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

// BrowserKind identifies the type of message sent from the browser to Go.
type BrowserKind int32

const (
	BrowserKind_BROWSER_INPUT        BrowserKind = 0
	BrowserKind_BROWSER_METHOD       BrowserKind = 1
	BrowserKind_BROWSER_JSRESULT     BrowserKind = 2
	BrowserKind_BROWSER_INIT_REQUEST BrowserKind = 3 // future
	BrowserKind_BROWSER_PAGE_INFO    BrowserKind = 4 // future
	BrowserKind_BROWSER_BROADCAST    BrowserKind = 5 // future
)

// Enum value maps for BrowserKind.
var (
	BrowserKind_name = map[int32]string{
		0: "BROWSER_INPUT",
		1: "BROWSER_METHOD",
		2: "BROWSER_JSRESULT",
		3: "BROWSER_INIT_REQUEST",
		4: "BROWSER_PAGE_INFO",
		5: "BROWSER_BROADCAST",
	}
	BrowserKind_value = map[string]int32{
		"BROWSER_INPUT":        0,
		"BROWSER_METHOD":       1,
		"BROWSER_JSRESULT":     2,
		"BROWSER_INIT_REQUEST": 3,
		"BROWSER_PAGE_INFO":    4,
		"BROWSER_BROADCAST":    5,
	}
)

func (x BrowserKind) Enum() *BrowserKind {
	p := new(BrowserKind)
	*p = x
	return p
}

func (x BrowserKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BrowserKind) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_enumTypes[1].Descriptor()
}

func (BrowserKind) Type() protoreflect.EnumType {
	return &file_protocol_proto_enumTypes[1]
}

func (x BrowserKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BrowserKind.Descriptor instead.
func (BrowserKind) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

// ServerMessage is the single message type sent from Go to the browser.
// The `kind` field determines which payload fields are relevant.
type ServerMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Kind   ServerKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=godom.ServerKind" json:"kind,omitempty"`
	Target string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // island instance name (for init, patch, stream)
	// VDOM fields (kind: INIT, PATCH)
	Tree    []byte      `protobuf:"bytes,10,opt,name=tree,proto3" json:"tree,omitempty"`       // JSON-encoded tree description (init only)
	Patches []*DomPatch `protobuf:"bytes,11,rep,name=patches,proto3" json:"patches,omitempty"` // incremental patches (patch only)
	// ExecJS fields (kind: JSCALL)
	CallId        int32  `protobuf:"varint,20,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"` // unique request ID for correlating responses
	Expr          string `protobuf:"bytes,21,opt,name=expr,proto3" json:"expr,omitempty"`                    // JavaScript expression to evaluate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *ServerMessage) GetKind() ServerKind {
	if x != nil {
		return x.Kind
	}
	return ServerKind_SERVER_INIT
}

func (x *ServerMessage) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ServerMessage) GetTree() []byte {
	if x != nil {
		return x.Tree
	}
	return nil
}

func (x *ServerMessage) GetPatches() []*DomPatch {
	if x != nil {
		return x.Patches
	}
	return nil
}

func (x *ServerMessage) GetCallId() int32 {
	if x != nil {
		return x.CallId
	}
	return 0
}

func (x *ServerMessage) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

// DomPatch describes a single DOM mutation produced by the diff algorithm.
type DomPatch struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable node ID (assigned by Go, maps to nodeMap on bridge)
	Op     string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`                        // patch operation type
	// Type-specific payloads:
	Text          string      `protobuf:"bytes,10,opt,name=text,proto3" json:"text,omitempty"`                                  // patchText: new text content
	Facts         []byte      `protobuf:"bytes,11,opt,name=facts,proto3" json:"facts,omitempty"`                                // patchFacts: JSON-encoded FactsDiff
	TreeContent   []byte      `protobuf:"bytes,12,opt,name=tree_content,json=treeContent,proto3" json:"tree_content,omitempty"` // patchRedraw/patchAppend: JSON-encoded tree description
	Count         int32       `protobuf:"varint,13,opt,name=count,proto3" json:"count,omitempty"`                               // patchRemoveLast: number of children to remove
	Reorder       []byte      `protobuf:"bytes,14,opt,name=reorder,proto3" json:"reorder,omitempty"`                            // patchReorder: JSON-encoded reorder ops with tree descriptions
	PluginData    []byte      `protobuf:"bytes,15,opt,name=plugin_data,json=pluginData,proto3" json:"plugin_data,omitempty"`    // patchPlugin: JSON-encoded plugin data
	SubPatches    []*DomPatch `protobuf:"bytes,16,rep,name=sub_patches,json=subPatches,proto3" json:"sub_patches,omitempty"`    // patchLazy: patches inside lazy node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomPatch) Reset() {
	*x = DomPatch{}
	mi := &file_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomPatch) ProtoMessage() {}

func (x *DomPatch) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomPatch.ProtoReflect.Descriptor instead.
func (*DomPatch) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *DomPatch) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *DomPatch) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *DomPatch) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DomPatch) GetFacts() []byte {
	if x != nil {
		return x.Facts
	}
	return nil
}

func (x *DomPatch) GetTreeContent() []byte {
	if x != nil {
		return x.TreeContent
	}
	return nil
}

func (x *DomPatch) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DomPatch) GetReorder() []byte {
	if x != nil {
		return x.Reorder
	}
	return nil
}

func (x *DomPatch) GetPluginData() []byte {
	if x != nil {
		return x.PluginData
	}
	return nil
}

func (x *DomPatch) GetSubPatches() []*DomPatch {
	if x != nil {
		return x.SubPatches
	}
	return nil
}

// BrowserMessage is the single message type sent from the browser to Go.
// The `kind` field determines which payload fields are relevant.
type BrowserMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Kind   BrowserKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=godom.BrowserKind" json:"kind,omitempty"`
	NodeId int32                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // source node (0 = none, e.g. godom.call)
	// Input sync fields (kind: INPUT)
	Value string `protobuf:"bytes,10,opt,name=value,proto3" json:"value,omitempty"` // current DOM value (e.g. input.value)
	// Method call fields (kind: METHOD)
	Method string   `protobuf:"bytes,20,opt,name=method,proto3" json:"method,omitempty"` // Go method name (e.g. "AddTodo", "Toggle")
	Args   [][]byte `protobuf:"bytes,21,rep,name=args,proto3" json:"args,omitempty"`     // JSON-encoded arguments
	// JSResult fields (kind: JSRESULT)
	CallId int32  `protobuf:"varint,30,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"` // matches the ServerMessage.call_id
	Result []byte `protobuf:"bytes,31,opt,name=result,proto3" json:"result,omitempty"`                // JSON-encoded result value
	Error  string `protobuf:"bytes,32,opt,name=error,proto3" json:"error,omitempty"`                  // error message if eval failed
	// Init request fields (kind: INIT_REQUEST)
	Island        string `protobuf:"bytes,40,opt,name=island,proto3" json:"island,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserMessage) Reset() {
	*x = BrowserMessage{}
	mi := &file_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserMessage) ProtoMessage() {}

func (x *BrowserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserMessage.ProtoReflect.Descriptor instead.
func (*BrowserMessage) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *BrowserMessage) GetKind() BrowserKind {
	if x != nil {
		return x.Kind
	}
	return BrowserKind_BROWSER_INPUT
}

func (x *BrowserMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *BrowserMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *BrowserMessage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *BrowserMessage) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *BrowserMessage) GetCallId() int32 {
	if x != nil {
		return x.CallId
	}
	return 0
}

func (x *BrowserMessage) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *BrowserMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BrowserMessage) GetIsland() string {
	if x != nil {
		return x.Island
	}
	return ""
}

var File_protocol_proto protoreflect.FileDescriptor

const file_protocol_proto_rawDesc = "" +
	"\n" +
	"\x0eprotocol.proto\x12\x05godom\"\xba\x01\n" +
	"\rServerMessage\x12%\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x11.godom.ServerKindR\x04kind\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04tree\x18\n" +
	" \x01(\fR\x04tree\x12)\n" +
	"\apatches\x18\v \x03(\v2\x0f.godom.DomPatchR\apatches\x12\x17\n" +
	"\acall_id\x18\x14 \x01(\x05R\x06callId\x12\x12\n" +
	"\x04expr\x18\x15 \x01(\tR\x04expr\"\x83\x02\n" +
	"\bDomPatch\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x12\n" +
	"\x04text\x18\n" +
	" \x01(\tR\x04text\x12\x14\n" +
	"\x05facts\x18\v \x01(\fR\x05facts\x12!\n" +
	"\ftree_content\x18\f \x01(\fR\vtreeContent\x12\x14\n" +
	"\x05count\x18\r \x01(\x05R\x05count\x12\x18\n" +
	"\areorder\x18\x0e \x01(\fR\areorder\x12\x1f\n" +
	"\vplugin_data\x18\x0f \x01(\fR\n" +
	"pluginData\x120\n" +
	"\vsub_patches\x18\x10 \x03(\v2\x0f.godom.DomPatchR\n" +
	"subPatches\"\xf2\x01\n" +
	"\x0eBrowserMessage\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.godom.BrowserKindR\x04kind\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x05R\x06nodeId\x12\x14\n" +
	"\x05value\x18\n" +
	" \x01(\tR\x05value\x12\x16\n" +
	"\x06method\x18\x14 \x01(\tR\x06method\x12\x12\n" +
	"\x04args\x18\x15 \x03(\fR\x04args\x12\x17\n" +
	"\acall_id\x18\x1e \x01(\x05R\x06callId\x12\x16\n" +
	"\x06result\x18\x1f \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18  \x01(\tR\x05error\x12\x16\n" +
	"\x06island\x18( \x01(\tR\x06island*k\n" +
	"\n" +
	"ServerKind\x12\x0f\n" +
	"\vSERVER_INIT\x10\x00\x12\x10\n" +
	"\fSERVER_PATCH\x10\x01\x12\x11\n" +
	"\rSERVER_JSCALL\x10\x02\x12\x11\n" +
	"\rSERVER_STREAM\x10\x03\x12\x14\n" +
	"\x10SERVER_BROADCAST\x10\x04*\x92\x01\n" +
	"\vBrowserKind\x12\x11\n" +
	"\rBROWSER_INPUT\x10\x00\x12\x12\n" +
	"\x0eBROWSER_METHOD\x10\x01\x12\x14\n" +
	"\x10BROWSER_JSRESULT\x10\x02\x12\x18\n" +
	"\x14BROWSER_INIT_REQUEST\x10\x03\x12\x15\n" +
	"\x11BROWSER_PAGE_INFO\x10\x04\x12\x15\n" +
	"\x11BROWSER_BROADCAST\x10\x05B\tZ\a./protob\x06proto3"

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData []byte
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)))
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protocol_proto_goTypes = []any{
	(ServerKind)(0),        // 0: godom.ServerKind
	(BrowserKind)(0),       // 1: godom.BrowserKind
	(*ServerMessage)(nil),  // 2: godom.ServerMessage
	(*DomPatch)(nil),       // 3: godom.DomPatch
	(*BrowserMessage)(nil), // 4: godom.BrowserMessage
}
var file_protocol_proto_depIdxs = []int32{
	0, // 0: godom.ServerMessage.kind:type_name -> godom.ServerKind
	3, // 1: godom.ServerMessage.patches:type_name -> godom.DomPatch
	3, // 2: godom.DomPatch.sub_patches:type_name -> godom.DomPatch
	1, // 3: godom.BrowserMessage.kind:type_name -> godom.BrowserKind
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		EnumInfos:         file_protocol_proto_enumTypes,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}
