// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protocol.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerMessage is the single message type sent from Go to the browser.
// The `kind` field determines which payload fields are relevant.
type ServerMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Kind   string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`     // "init", "patch", "jscall", "stream" (future), "broadcast" (future)
	Target string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // component instance name (for init, patch, stream)
	// VDOM fields (kind: "init", "patch")
	Tree    []byte      `protobuf:"bytes,10,opt,name=tree,proto3" json:"tree,omitempty"`       // JSON-encoded tree description (init only)
	Patches []*DomPatch `protobuf:"bytes,11,rep,name=patches,proto3" json:"patches,omitempty"` // incremental patches (patch only)
	// ExecJS fields (kind: "jscall")
	CallId        int32  `protobuf:"varint,20,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"` // unique request ID for correlating responses
	Expr          string `protobuf:"bytes,21,opt,name=expr,proto3" json:"expr,omitempty"`                    // JavaScript expression to evaluate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *ServerMessage) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ServerMessage) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ServerMessage) GetTree() []byte {
	if x != nil {
		return x.Tree
	}
	return nil
}

func (x *ServerMessage) GetPatches() []*DomPatch {
	if x != nil {
		return x.Patches
	}
	return nil
}

func (x *ServerMessage) GetCallId() int32 {
	if x != nil {
		return x.CallId
	}
	return 0
}

func (x *ServerMessage) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

// DomPatch describes a single DOM mutation produced by the diff algorithm.
type DomPatch struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // stable node ID (assigned by Go, maps to nodeMap on bridge)
	Op     string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`                        // patch operation type
	// Type-specific payloads:
	Text          string      `protobuf:"bytes,10,opt,name=text,proto3" json:"text,omitempty"`                                  // patchText: new text content
	Facts         []byte      `protobuf:"bytes,11,opt,name=facts,proto3" json:"facts,omitempty"`                                // patchFacts: JSON-encoded FactsDiff
	TreeContent   []byte      `protobuf:"bytes,12,opt,name=tree_content,json=treeContent,proto3" json:"tree_content,omitempty"` // patchRedraw/patchAppend: JSON-encoded tree description
	Count         int32       `protobuf:"varint,13,opt,name=count,proto3" json:"count,omitempty"`                               // patchRemoveLast: number of children to remove
	Reorder       []byte      `protobuf:"bytes,14,opt,name=reorder,proto3" json:"reorder,omitempty"`                            // patchReorder: JSON-encoded reorder ops with tree descriptions
	PluginData    []byte      `protobuf:"bytes,15,opt,name=plugin_data,json=pluginData,proto3" json:"plugin_data,omitempty"`    // patchPlugin: JSON-encoded plugin data
	SubPatches    []*DomPatch `protobuf:"bytes,16,rep,name=sub_patches,json=subPatches,proto3" json:"sub_patches,omitempty"`    // patchLazy: patches inside lazy node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomPatch) Reset() {
	*x = DomPatch{}
	mi := &file_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomPatch) ProtoMessage() {}

func (x *DomPatch) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomPatch.ProtoReflect.Descriptor instead.
func (*DomPatch) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *DomPatch) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *DomPatch) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *DomPatch) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DomPatch) GetFacts() []byte {
	if x != nil {
		return x.Facts
	}
	return nil
}

func (x *DomPatch) GetTreeContent() []byte {
	if x != nil {
		return x.TreeContent
	}
	return nil
}

func (x *DomPatch) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DomPatch) GetReorder() []byte {
	if x != nil {
		return x.Reorder
	}
	return nil
}

func (x *DomPatch) GetPluginData() []byte {
	if x != nil {
		return x.PluginData
	}
	return nil
}

func (x *DomPatch) GetSubPatches() []*DomPatch {
	if x != nil {
		return x.SubPatches
	}
	return nil
}

// BrowserMessage is the single message type sent from the browser to Go.
// The `kind` field determines which payload fields are relevant.
type BrowserMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Kind   string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`                    // "input", "method", "jsresult", "init_request" (future), "page_info" (future), "broadcast" (future)
	NodeId int32                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // source node (0 = none, e.g. godom.call)
	// Input sync fields (kind: "input")
	Value string `protobuf:"bytes,10,opt,name=value,proto3" json:"value,omitempty"` // current DOM value (e.g. input.value)
	// Method call fields (kind: "method")
	Method string   `protobuf:"bytes,20,opt,name=method,proto3" json:"method,omitempty"` // Go method name (e.g. "AddTodo", "Toggle")
	Args   [][]byte `protobuf:"bytes,21,rep,name=args,proto3" json:"args,omitempty"`     // JSON-encoded arguments
	// JSResult fields (kind: "jsresult")
	CallId        int32  `protobuf:"varint,30,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"` // matches the ServerMessage.call_id
	Result        []byte `protobuf:"bytes,31,opt,name=result,proto3" json:"result,omitempty"`                // JSON-encoded result value
	Error         string `protobuf:"bytes,32,opt,name=error,proto3" json:"error,omitempty"`                  // error message if eval failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserMessage) Reset() {
	*x = BrowserMessage{}
	mi := &file_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserMessage) ProtoMessage() {}

func (x *BrowserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserMessage.ProtoReflect.Descriptor instead.
func (*BrowserMessage) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *BrowserMessage) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *BrowserMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *BrowserMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *BrowserMessage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *BrowserMessage) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *BrowserMessage) GetCallId() int32 {
	if x != nil {
		return x.CallId
	}
	return 0
}

func (x *BrowserMessage) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *BrowserMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_protocol_proto protoreflect.FileDescriptor

const file_protocol_proto_rawDesc = "" +
	"\n" +
	"\x0eprotocol.proto\x12\x05godom\"\xa7\x01\n" +
	"\rServerMessage\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04tree\x18\n" +
	" \x01(\fR\x04tree\x12)\n" +
	"\apatches\x18\v \x03(\v2\x0f.godom.DomPatchR\apatches\x12\x17\n" +
	"\acall_id\x18\x14 \x01(\x05R\x06callId\x12\x12\n" +
	"\x04expr\x18\x15 \x01(\tR\x04expr\"\x83\x02\n" +
	"\bDomPatch\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x12\n" +
	"\x04text\x18\n" +
	" \x01(\tR\x04text\x12\x14\n" +
	"\x05facts\x18\v \x01(\fR\x05facts\x12!\n" +
	"\ftree_content\x18\f \x01(\fR\vtreeContent\x12\x14\n" +
	"\x05count\x18\r \x01(\x05R\x05count\x12\x18\n" +
	"\areorder\x18\x0e \x01(\fR\areorder\x12\x1f\n" +
	"\vplugin_data\x18\x0f \x01(\fR\n" +
	"pluginData\x120\n" +
	"\vsub_patches\x18\x10 \x03(\v2\x0f.godom.DomPatchR\n" +
	"subPatches\"\xc6\x01\n" +
	"\x0eBrowserMessage\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x05R\x06nodeId\x12\x14\n" +
	"\x05value\x18\n" +
	" \x01(\tR\x05value\x12\x16\n" +
	"\x06method\x18\x14 \x01(\tR\x06method\x12\x12\n" +
	"\x04args\x18\x15 \x03(\fR\x04args\x12\x17\n" +
	"\acall_id\x18\x1e \x01(\x05R\x06callId\x12\x16\n" +
	"\x06result\x18\x1f \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18  \x01(\tR\x05errorB\tZ\a./protob\x06proto3"

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData []byte
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)))
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protocol_proto_goTypes = []any{
	(*ServerMessage)(nil),  // 0: godom.ServerMessage
	(*DomPatch)(nil),       // 1: godom.DomPatch
	(*BrowserMessage)(nil), // 2: godom.BrowserMessage
}
var file_protocol_proto_depIdxs = []int32{
	1, // 0: godom.ServerMessage.patches:type_name -> godom.DomPatch
	1, // 1: godom.DomPatch.sub_patches:type_name -> godom.DomPatch
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}
