// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protocol.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerMessage is the top-level message sent from Go to the browser.
type ServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "init" or "update"
	Commands      []*Command             `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	Events        []*EventCommand        `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *ServerMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServerMessage) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *ServerMessage) GetEvents() []*EventCommand {
	if x != nil {
		return x.Events
	}
	return nil
}

// Command is a single DOM operation.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Op    string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`     // "text","value","checked","display","class","attr","style","plugin","list","list-append","list-truncate","re-event"
	Id    string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`     // data-gid of target element
	Name  string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // class name (for "class" op), attr name, style property name, plugin name
	// Types that are valid to be assigned to Val:
	//
	//	*Command_StrVal
	//	*Command_BoolVal
	//	*Command_NumVal
	//	*Command_RawVal
	Val           isCommand_Val `protobuf_oneof:"val"`
	Items         []*ListItem   `protobuf:"bytes,8,rep,name=items,proto3" json:"items,omitempty"` // for "list" and "list-append" ops
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Command) GetVal() isCommand_Val {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *Command) GetStrVal() string {
	if x != nil {
		if x, ok := x.Val.(*Command_StrVal); ok {
			return x.StrVal
		}
	}
	return ""
}

func (x *Command) GetBoolVal() bool {
	if x != nil {
		if x, ok := x.Val.(*Command_BoolVal); ok {
			return x.BoolVal
		}
	}
	return false
}

func (x *Command) GetNumVal() float64 {
	if x != nil {
		if x, ok := x.Val.(*Command_NumVal); ok {
			return x.NumVal
		}
	}
	return 0
}

func (x *Command) GetRawVal() []byte {
	if x != nil {
		if x, ok := x.Val.(*Command_RawVal); ok {
			return x.RawVal
		}
	}
	return nil
}

func (x *Command) GetItems() []*ListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type isCommand_Val interface {
	isCommand_Val()
}

type Command_StrVal struct {
	StrVal string `protobuf:"bytes,4,opt,name=str_val,json=strVal,proto3,oneof"`
}

type Command_BoolVal struct {
	BoolVal bool `protobuf:"varint,5,opt,name=bool_val,json=boolVal,proto3,oneof"`
}

type Command_NumVal struct {
	NumVal float64 `protobuf:"fixed64,6,opt,name=num_val,json=numVal,proto3,oneof"`
}

type Command_RawVal struct {
	RawVal []byte `protobuf:"bytes,7,opt,name=raw_val,json=rawVal,proto3,oneof"` // JSON bytes for plugin data, re-event, etc.
}

func (*Command_StrVal) isCommand_Val() {}

func (*Command_BoolVal) isCommand_Val() {}

func (*Command_NumVal) isCommand_Val() {}

func (*Command_RawVal) isCommand_Val() {}

// ListItem is a single item in a g-for list render.
type ListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Html          string                 `protobuf:"bytes,1,opt,name=html,proto3" json:"html,omitempty"`
	Cmds          []*Command             `protobuf:"bytes,2,rep,name=cmds,proto3" json:"cmds,omitempty"`
	Evts          []*EventCommand        `protobuf:"bytes,3,rep,name=evts,proto3" json:"evts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItem) Reset() {
	*x = ListItem{}
	mi := &file_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItem) ProtoMessage() {}

func (x *ListItem) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItem.ProtoReflect.Descriptor instead.
func (*ListItem) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *ListItem) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *ListItem) GetCmds() []*Command {
	if x != nil {
		return x.Cmds
	}
	return nil
}

func (x *ListItem) GetEvts() []*EventCommand {
	if x != nil {
		return x.Evts
	}
	return nil
}

// EventCommand describes an event listener the bridge should register.
type EventCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`   // data-gid
	On            string                 `protobuf:"bytes,2,opt,name=on,proto3" json:"on,omitempty"`   // "click","keydown","mousedown","mousemove","mouseup","wheel","input"
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"` // key filter for keydown
	Msg           []byte                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"` // pre-built Envelope.msg bytes — bridge sends back untouched
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventCommand) Reset() {
	*x = EventCommand{}
	mi := &file_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCommand) ProtoMessage() {}

func (x *EventCommand) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventCommand.ProtoReflect.Descriptor instead.
func (*EventCommand) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *EventCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventCommand) GetOn() string {
	if x != nil {
		return x.On
	}
	return ""
}

func (x *EventCommand) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EventCommand) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

// VDomMessage is the top-level message for the VDOM pipeline.
type VDomMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // "init" or "patch"
	Html          []byte                 `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty"`       // full rendered HTML (init only)
	Patches       []*DomPatch            `protobuf:"bytes,3,rep,name=patches,proto3" json:"patches,omitempty"` // incremental patches (patch only)
	Events        []*EventSetup          `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`   // event listener registrations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VDomMessage) Reset() {
	*x = VDomMessage{}
	mi := &file_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VDomMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VDomMessage) ProtoMessage() {}

func (x *VDomMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VDomMessage.ProtoReflect.Descriptor instead.
func (*VDomMessage) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *VDomMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VDomMessage) GetHtml() []byte {
	if x != nil {
		return x.Html
	}
	return nil
}

func (x *VDomMessage) GetPatches() []*DomPatch {
	if x != nil {
		return x.Patches
	}
	return nil
}

func (x *VDomMessage) GetEvents() []*EventSetup {
	if x != nil {
		return x.Events
	}
	return nil
}

// DomPatch describes a single DOM mutation produced by the diff algorithm.
type DomPatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // depth-first traversal index of target node
	Op    string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`        // patch operation type
	// Type-specific payloads:
	Text          string        `protobuf:"bytes,10,opt,name=text,proto3" json:"text,omitempty"`                                  // patchText: new text content
	Facts         []byte        `protobuf:"bytes,11,opt,name=facts,proto3" json:"facts,omitempty"`                                // patchFacts: JSON-encoded FactsDiff
	HtmlContent   []byte        `protobuf:"bytes,12,opt,name=html_content,json=htmlContent,proto3" json:"html_content,omitempty"` // patchRedraw/patchAppend: rendered HTML
	Count         int32         `protobuf:"varint,13,opt,name=count,proto3" json:"count,omitempty"`                               // patchRemoveLast: number of children to remove
	Reorder       []byte        `protobuf:"bytes,14,opt,name=reorder,proto3" json:"reorder,omitempty"`                            // patchReorder: JSON-encoded {inserts, removes}
	PluginData    []byte        `protobuf:"bytes,15,opt,name=plugin_data,json=pluginData,proto3" json:"plugin_data,omitempty"`    // patchPlugin: JSON-encoded plugin data
	SubPatches    []*DomPatch   `protobuf:"bytes,16,rep,name=sub_patches,json=subPatches,proto3" json:"sub_patches,omitempty"`    // patchLazy: patches inside lazy node
	PatchEvents   []*EventSetup `protobuf:"bytes,17,rep,name=patch_events,json=patchEvents,proto3" json:"patch_events,omitempty"` // events for newly rendered nodes (redraw/append)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomPatch) Reset() {
	*x = DomPatch{}
	mi := &file_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomPatch) ProtoMessage() {}

func (x *DomPatch) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomPatch.ProtoReflect.Descriptor instead.
func (*DomPatch) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *DomPatch) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DomPatch) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *DomPatch) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DomPatch) GetFacts() []byte {
	if x != nil {
		return x.Facts
	}
	return nil
}

func (x *DomPatch) GetHtmlContent() []byte {
	if x != nil {
		return x.HtmlContent
	}
	return nil
}

func (x *DomPatch) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DomPatch) GetReorder() []byte {
	if x != nil {
		return x.Reorder
	}
	return nil
}

func (x *DomPatch) GetPluginData() []byte {
	if x != nil {
		return x.PluginData
	}
	return nil
}

func (x *DomPatch) GetSubPatches() []*DomPatch {
	if x != nil {
		return x.SubPatches
	}
	return nil
}

func (x *DomPatch) GetPatchEvents() []*EventSetup {
	if x != nil {
		return x.PatchEvents
	}
	return nil
}

// EventSetup describes an event listener the bridge should register.
// Similar to EventCommand but with additional options.
type EventSetup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Gid             string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`     // data-gid of target element
	Event           string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"` // "click","keydown","input", etc.
	Key             string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`     // key filter for keydown
	Msg             []byte                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`     // pre-built WSMessage bytes
	StopPropagation bool                   `protobuf:"varint,5,opt,name=stop_propagation,json=stopPropagation,proto3" json:"stop_propagation,omitempty"`
	PreventDefault  bool                   `protobuf:"varint,6,opt,name=prevent_default,json=preventDefault,proto3" json:"prevent_default,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EventSetup) Reset() {
	*x = EventSetup{}
	mi := &file_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSetup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSetup) ProtoMessage() {}

func (x *EventSetup) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSetup.ProtoReflect.Descriptor instead.
func (*EventSetup) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *EventSetup) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *EventSetup) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *EventSetup) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EventSetup) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *EventSetup) GetStopPropagation() bool {
	if x != nil {
		return x.StopPropagation
	}
	return false
}

func (x *EventSetup) GetPreventDefault() bool {
	if x != nil {
		return x.PreventDefault
	}
	return false
}

// Envelope is what the bridge sends to Go on every event.
// The bridge never opens msg — it forwards it untouched.
// args carries browser-side data (mouse coords, wheel delta).
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []float64              `protobuf:"fixed64,1,rep,packed,name=args,proto3" json:"args,omitempty"` // browser-side args (mouse x/y, wheel deltaY)
	Msg           []byte                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`            // pre-built WSMessage bytes from Go
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`        // input value for bind events (JSON-encoded)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *Envelope) GetArgs() []float64 {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Envelope) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Envelope) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// WSMessage is the inner message pre-built by Go at render time.
// Serialized into EventCommand.msg and Envelope.msg.
type WSMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "call" or "bind"
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Args          [][]byte               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`   // pre-resolved args, each JSON-encoded
	Field         string                 `protobuf:"bytes,4,opt,name=field,proto3" json:"field,omitempty"` // field name (for bind)
	Value         []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"` // new value (for bind, added by bridge)
	Scope         string                 `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"` // "forGID:idx" for child components
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSMessage) Reset() {
	*x = WSMessage{}
	mi := &file_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSMessage) ProtoMessage() {}

func (x *WSMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSMessage.ProtoReflect.Descriptor instead.
func (*WSMessage) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *WSMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WSMessage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *WSMessage) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *WSMessage) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *WSMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WSMessage) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

var File_protocol_proto protoreflect.FileDescriptor

const file_protocol_proto_rawDesc = "" +
	"\n" +
	"\x0eprotocol.proto\x12\x05godom\"|\n" +
	"\rServerMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12*\n" +
	"\bcommands\x18\x02 \x03(\v2\x0e.godom.CommandR\bcommands\x12+\n" +
	"\x06events\x18\x03 \x03(\v2\x13.godom.EventCommandR\x06events\"\xd9\x01\n" +
	"\aCommand\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\astr_val\x18\x04 \x01(\tH\x00R\x06strVal\x12\x1b\n" +
	"\bbool_val\x18\x05 \x01(\bH\x00R\aboolVal\x12\x19\n" +
	"\anum_val\x18\x06 \x01(\x01H\x00R\x06numVal\x12\x19\n" +
	"\araw_val\x18\a \x01(\fH\x00R\x06rawVal\x12%\n" +
	"\x05items\x18\b \x03(\v2\x0f.godom.ListItemR\x05itemsB\x05\n" +
	"\x03val\"k\n" +
	"\bListItem\x12\x12\n" +
	"\x04html\x18\x01 \x01(\tR\x04html\x12\"\n" +
	"\x04cmds\x18\x02 \x03(\v2\x0e.godom.CommandR\x04cmds\x12'\n" +
	"\x04evts\x18\x03 \x03(\v2\x13.godom.EventCommandR\x04evts\"R\n" +
	"\fEventCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02on\x18\x02 \x01(\tR\x02on\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\fR\x03msg\"\x8b\x01\n" +
	"\vVDomMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04html\x18\x02 \x01(\fR\x04html\x12)\n" +
	"\apatches\x18\x03 \x03(\v2\x0f.godom.DomPatchR\apatches\x12)\n" +
	"\x06events\x18\x04 \x03(\v2\x11.godom.EventSetupR\x06events\"\xb6\x02\n" +
	"\bDomPatch\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x12\n" +
	"\x04text\x18\n" +
	" \x01(\tR\x04text\x12\x14\n" +
	"\x05facts\x18\v \x01(\fR\x05facts\x12!\n" +
	"\fhtml_content\x18\f \x01(\fR\vhtmlContent\x12\x14\n" +
	"\x05count\x18\r \x01(\x05R\x05count\x12\x18\n" +
	"\areorder\x18\x0e \x01(\fR\areorder\x12\x1f\n" +
	"\vplugin_data\x18\x0f \x01(\fR\n" +
	"pluginData\x120\n" +
	"\vsub_patches\x18\x10 \x03(\v2\x0f.godom.DomPatchR\n" +
	"subPatches\x124\n" +
	"\fpatch_events\x18\x11 \x03(\v2\x11.godom.EventSetupR\vpatchEvents\"\xac\x01\n" +
	"\n" +
	"EventSetup\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\fR\x03msg\x12)\n" +
	"\x10stop_propagation\x18\x05 \x01(\bR\x0fstopPropagation\x12'\n" +
	"\x0fprevent_default\x18\x06 \x01(\bR\x0epreventDefault\"F\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04args\x18\x01 \x03(\x01R\x04args\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\fR\x03msg\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\x8d\x01\n" +
	"\tWSMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04args\x18\x03 \x03(\fR\x04args\x12\x14\n" +
	"\x05field\x18\x04 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12\x14\n" +
	"\x05scope\x18\x06 \x01(\tR\x05scopeB\n" +
	"Z\b./;godomb\x06proto3"

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData []byte
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)))
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protocol_proto_goTypes = []any{
	(*ServerMessage)(nil), // 0: godom.ServerMessage
	(*Command)(nil),       // 1: godom.Command
	(*ListItem)(nil),      // 2: godom.ListItem
	(*EventCommand)(nil),  // 3: godom.EventCommand
	(*VDomMessage)(nil),   // 4: godom.VDomMessage
	(*DomPatch)(nil),      // 5: godom.DomPatch
	(*EventSetup)(nil),    // 6: godom.EventSetup
	(*Envelope)(nil),      // 7: godom.Envelope
	(*WSMessage)(nil),     // 8: godom.WSMessage
}
var file_protocol_proto_depIdxs = []int32{
	1, // 0: godom.ServerMessage.commands:type_name -> godom.Command
	3, // 1: godom.ServerMessage.events:type_name -> godom.EventCommand
	2, // 2: godom.Command.items:type_name -> godom.ListItem
	1, // 3: godom.ListItem.cmds:type_name -> godom.Command
	3, // 4: godom.ListItem.evts:type_name -> godom.EventCommand
	5, // 5: godom.VDomMessage.patches:type_name -> godom.DomPatch
	6, // 6: godom.VDomMessage.events:type_name -> godom.EventSetup
	5, // 7: godom.DomPatch.sub_patches:type_name -> godom.DomPatch
	6, // 8: godom.DomPatch.patch_events:type_name -> godom.EventSetup
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	file_protocol_proto_msgTypes[1].OneofWrappers = []any{
		(*Command_StrVal)(nil),
		(*Command_BoolVal)(nil),
		(*Command_NumVal)(nil),
		(*Command_RawVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}
